Feature/pages transitions
Studio-024/projeto01 pull request #21
Opened 2021-07-31 17:21 UTC by AlexandreXYZ

Add pages transition for React-routes

2021-07-31 17:40 UTC, ViniciusGregorine reviewed
"ta no caminho"

2021-07-31 17:40 UTC, ViniciusGregorine commented on client/src/App.tsx
> +	const [getDashbortType, setDashboardType] = useState('Dashboard')
**possibilidade** da retirada disso

2021-07-31 18:29 UTC, AlexandreXYZ commented on client/src/App.tsx
> +	const [getDashbortType, setDashboardType] = useState('Dashboard')
Resolvido no commit 49e7046

2021-08-05 18:58 UTC, ViniciusGregorine approved these changes
all good

2021-08-05 19:00 UTC, k1vz requested changes
Tá ótimo, só dá uma olhada nos comentários antes de dar merge

2021-08-05 19:00 UTC, k1vz commented on client/src/components/Add.tsx
> +            { side === 'front' && <div id="AddContainer_title">
dá uma revisada nessa identação das chaves aq, tipo coloca igual as chaves de 'if' tlg

2021-08-05 19:00 UTC, k1vz commented on client/src/components/Revision.tsx
> +const Revision = ({dataCards, buttonIndex,}: Props) => {
tem uma vírgula a mais ali

2021-08-05 19:00 UTC, k1vz commented on client/src/css/AddCard.css
>    background-color: #ebf5ff; }
fecha chaves precisa de atenção dnv

2021-08-05 19:00 UTC, k1vz commented on client/src/css/Revision.css
> +  .card_footer > a {
'a'?

2021-08-05 19:00 UTC, k1vz commented on client/src/index.tsx
> +import { BrowserRouter as Router} from "react-router-dom";
faltou um espaço dps do Router

2021-08-05 19:00 UTC, k1vz commented on client/src/index.tsx
>    </React.StrictMode>,
Tem uma vírgula ali no fim

2021-08-05 19:00 UTC, k1vz commented on client/src/pages/Dashboard.tsx
> +                        <RevisionQuest dataCards={orderCards} buttonIndex={index}/>
aq ainda ta usando como 'quest' e 'response', n seria interessante mudar pra 'front' e 'back' tb?

2021-08-05 19:03 UTC, AlexandreXYZ commented on client/src/components/Add.tsx
> +            { side === 'front' && <div id="AddContainer_title">
Você diz tipo:
`{side === 'front && 
<div>...</div>}`?

2021-08-05 19:05 UTC, AlexandreXYZ commented on client/src/components/Revision.tsx
> +const Revision = ({dataCards, buttonIndex,}: Props) => {
kkkkkkkkkk vlw

2021-08-05 19:06 UTC, AlexandreXYZ commented on client/src/css/AddCard.css
>    background-color: #ebf5ff; }
Os arquivos css são pré processados pelo SASS então isso não fui eu que fiz, é um resuldado dos meus codigos SASS.

2021-08-05 19:09 UTC, AlexandreXYZ commented on client/src/css/Revision.css
> +  .card_footer > a {
kkkkkkkkk é a tag html Link (um component do react-router-dom) que quando é transfomado em HTML vira uma tag "a" de ancora.

2021-08-05 19:14 UTC, AlexandreXYZ commented on client/src/index.tsx
>    </React.StrictMode>,
Se tu perceber não foi uma linha editada ksksksksks mas é pq ele não é um component como a gente usa tipo:
```
Return(
<div>...</div>
)
```
Mas é p ReactDOM.render, então ele tem algumas tag de config tipo o StrictMode, Router... mas se ver tem JS tambem que é oq vem depois da virgura:
```
ReactDOM.render(
  <React.StrictMode>
    <Router>
      <App/>
    </Router>
  </React.StrictMode>,
  document.getElementById('root') 
)
```
Resumindo: se tirar dá merda :)

2021-08-05 19:15 UTC, AlexandreXYZ commented on client/src/pages/Dashboard.tsx
> +                        <RevisionQuest dataCards={orderCards} buttonIndex={index}/>
Isso é só mesmo algo de interpretação no HTML, pra ti saber qual tag é qual, não faz diferença.

2021-08-05 19:41 UTC, k1vz commented on client/src/components/Add.tsx
> +            { side === 'front' && <div id="AddContainer_title">
tipo
```
{
side === 'front' && <div id="AddContainer_title">
```

2021-08-05 19:42 UTC, k1vz approved these changes

2021-08-05 22:59 UTC, merged