feature/authentication
Studio-024/projeto01 pull request #31
Opened 2021-08-15 01:52 UTC by ViniciusGregorine

2021-08-19 14:12 UTC, k1vz commented on server/scripts/db/users.sql
> +	password VARCHAR(60) BINARY NOT NULL,
como funciona esse "binary"?

2021-08-19 14:22 UTC, k1vz approved these changes
top

2021-08-19 14:22 UTC, k1vz commented on server/src/data/contracts/chekAccountByEmail.ts
> +  export namespace CheckAccountByEmailRepository {
faltou um "c" no nome do arquivo

2021-08-19 14:22 UTC, k1vz commented on server/src/data/services/signupUserService.ts
> +        private readonly haser: Hasher
faltou um "h" na variavel

2021-08-19 17:46 UTC, AlexandreXYZ approved these changes

2021-08-20 17:48 UTC, AlexandreXYZ approved these changes

2021-08-23 00:28 UTC, ViniciusGregorine commented
@k1vz fiz algumas refatorações, as principais foram:

- [x] O token não continha o id do usuário em seu payload (É um parâmetro obrigatório, porque quebra outras rotas da API)
- [x] O response da rota estava fora de padrão das outras rotas

Foram modificações simples.

No mais, Excelente trabalho 👍😎

2021-08-23 20:06 UTC, AlexandreXYZ requested changes

2021-08-23 20:06 UTC, AlexandreXYZ commented on server/src/main/factories/listCardController.ts
> +import { repo } from "./mysqlCardRepo";
O nome tanto da variavel REPO quanto aos aquivos 'mysqlCard**Repo**' tá estranho, mesmo deixando um nome mais longo ficaria melhor.

2021-08-24 17:59 UTC, ViniciusGregorine commented on server/src/main/factories/listCardController.ts
> +import { repo } from "./mysqlCardRepo";
repo é um padrão pra objetos de repositórios

2021-08-24 18:29 UTC, AlexandreXYZ approved these changes

2021-08-24 18:30 UTC, merged